name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: cache-me
        key: ${{ runner.os }}-primes

    - name: Write cache-me
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: date > cache-me

    - name: Print cache-me
      run: cat cache-me

    - name: Save cache
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: cache-me
        key: ${{ runner.os }}-primes

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: cache-me
        key: ${{ runner.os }}-primes

    - name: Is hit?
      run: echo ${{ steps.cache-primes.outputs.cache-hit }}

    - name: Print cache-me
      run: cat cache-me
