name: cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: cache-me
        key: v1

    - name: Is hit?
      run: echo ${{ toJSON(steps.cache.outputs.cache-hit) }}

    - name: Write cache-me
      run: date > cache-me

    - name: Print cache-me
      run: cat cache-me

    - name: Save cache
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: cache-me
        key: v1

    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: cache-me
        key: v1

    - name: Is hit?
      run: echo ${{ toJSON(steps.restore-cache.outputs.cache-hit) }}

    - name: Print cache-me
      run: cat cache-me
