name: cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: cache-me
        key: v1

    - name: Is hit?
      run: echo ${{ toJSON(steps.cache.outputs.cache-hit) }}

    - name: Write cache-me
      run: date > cache-me

    - name: Print cache-me
      run: cat cache-me

    - name: Cache
      id: cache2
      uses: actions/cache@v4
      with:
        path: cache-me
        key: v1

    - name: Is hit?
      run: echo ${{ toJSON(steps.cache2.outputs.cache-hit) }}

    - name: Print cache-me
      run: cat cache-me
